[package]
name = "jueferu/zeworld"
description = "Data syncronization made easy"
authors = ["@Jueferu <jb7177786@gmail.com>"]
version = "0.2.0"
license = "MIT"
registry = "https://github.com/Jueferu/wally-index"
realm = "shared"
include = ["lib", "default.project.json"]
repository = "https://github.com/Jueferu/ZeWorld"

[dependencies]
Janitor = "howmanysmall/janitor@^1.18"